"""add invite_status and password_hash

Revision ID: c9aa126c92e4
Revises: 6194482dc4f2
Create Date: 2026-04-25 17:11:55.934262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9aa126c92e4'
down_revision: Union[str, Sequence[str], None] = '6194482dc4f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('invite_status', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'invite_status')
    # ### end Alembic commands ###
